[workspace]
members = [
    "external-lib",
    "test-crate",
    "test-crate-custom-lib-name",
    "test-crate-metadata-config",
    "test-reexports-crate",
    "test-type-exported-from-hidden-module",
]
