[package]
name = "test-hidden-module-reexported-type"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
external-lib = { path = "../external-lib" }
